import Image from "next/image";
import { ArrowRight } from "lucide-react";
import { Container } from "@/components/ui/container";
import { Section, SectionHeading } from "@/components/ui/section";
import { Reveal } from "@/components/ui/reveal";

const steps = [
  {
    step: "01",
    label: "Physical Section",
    title: "Cut-section photograph",
    description:
      "A physical tyre cut-section is photographed under controlled conditions.",
    src: "/products/section-scanner-cut-section.jpg",
    alt: "Photograph of a physical tyre cut-section against a dark background",
  },
  {
    step: "02",
    label: "Computer Vision",
    title: "Automated contour detection",
    description:
      "tAIre Section Scanner detects component contours, reinforcement layers and key engineering points.",
    src: "/products/section-scanner-detected-cut-section.jpg",
    alt: "Same tyre cut-section with computer vision detection points overlaid on component contours",
  },
  {
    step: "03",
    label: "CAD Construction",
    title: "Digital geometry in Section Designer +",
    description:
      "Detected geometry is reconstructed as structured, dimensioned CAD geometry in tAIre Designer Suite.",
    src: "/products/section-designer-plus.png",
    alt: "Digitized tyre section profile with construction layers generated by Section Designer +",
  },
];

export function ScanToCadFlow() {
  return (
    <Section>
      <Container>
        <Reveal>
          <SectionHeading
            eyebrow="From Photo to Geometry"
            title="Physical section to digital CAD, in three steps"
            description="tAIre Section Scanner turns a photograph of a physical tyre cut-section into structured, reusable digital geometry."
          />
        </Reveal>

        <div className="mt-12 flex flex-col gap-3 lg:flex-row lg:items-stretch lg:gap-0">
          {steps.map((item, index) => (
            <div key={item.step} className="flex flex-1 items-stretch">
              <Reveal delay={index * 100} className="flex-1">
                <article className="card-elevated flex h-full flex-col gap-4 rounded-md border border-border bg-surface-raised p-6">
                  <div className="relative aspect-[4/3] w-full overflow-hidden rounded-sm border border-border bg-background">
                    <Image
                      src={item.src}
                      alt={item.alt}
                      fill
                      sizes="(min-width: 1024px) 33vw, 100vw"
                      className="object-contain"
                    />
                  </div>
                  <div className="flex flex-col gap-2">
                    <span className="font-mono text-xs text-text-muted">
                      {item.step} · {item.label}
                    </span>
                    <h3 className="text-base font-semibold text-text-primary">
                      {item.title}
                    </h3>
                    <p className="text-sm leading-relaxed text-text-secondary">
                      {item.description}
                    </p>
                  </div>
                </article>
              </Reveal>
              {index < steps.length - 1 ? (
                <div className="flex items-center justify-center px-2 lg:px-3">
                  <ArrowRight
                    className="h-4 w-4 shrink-0 text-text-muted lg:rotate-0"
                    aria-hidden="true"
                  />
                </div>
              ) : null}
            </div>
          ))}
        </div>
      </Container>
    </Section>
  );
}
